bizint/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views


from . import views

app_name = 'bizint'
urlpatterns = [
    # ex: /bizint/
    path('', views.index, name='index'),
    # ex: /bizint/5
    path('<int:action_id>/', views.info, name='info'),
    # ex: /bizint/5/add
    path('<int:action_id>/add', views.add, name='add'),
    # ex: /api/actions
    path('api/actions', views.api_actions, name='api_actions'),
    path('login/', auth_views.LoginView.as_view(template_name='bizint/login.html'), name='login')
]

bizint_ng/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('bizint/', include('bizint.urls')),
    path('admin/', admin.site.urls),
]

bizint/models.py
import json

from django.db import models
from django.utils import timezone
from django.urls import reverse


class Action(models.Model):
    action_name = models.CharField(max_length=20)
    creation_date = models.DateTimeField(default=timezone.now)  # Not to call function, server will call on run

    def get_current_count(self):
        current_count = self.instance_set.count()
        return current_count

    def get_last(self):
        current_count = self.instance_set.last()
        return current_count

    def to_json(self):
        action_dict = {
            self.action_name: {
                "creation_date": self.creation_date.timestamp(),
                "current_count": self.get_current_count()
            }
        }
        return json.dumps(action_dict)

    def get_absolute_url(self):
        return reverse('bizint:info', args=[str(self.id)])

    def __str__(self):
        return self.action_name


class Instance(models.Model):
    action = models.ForeignKey(Action, on_delete=models.SET_NULL, null=True)
    count = models.IntegerField(default=0)
    up_date = models.DateTimeField('date updated', default=timezone.now) # Not to call function, server will call on run
    note = models.CharField(default="", max_length=200)

    def __str__(self):
        return str(self.count)

bizint/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect

from .models import Action, Instance


def index(request):
    actions = Action.objects.all()
    context = {
        "action_list": actions,
    }
    return render(request, 'bizint/index.html', context)


def info(request, action_id):
    action = get_object_or_404(Action, pk=action_id)
    context = {
        "action": action,
    }
    return render(request, 'bizint/info.html', context)


## PROTOTYPE ##
def add(request, action_id):
    action = get_object_or_404(Action, pk=action_id)
    action.instance_set.create(action=action, count=action.get_current_count() + 1)

    return redirect(action.get_absolute_url())


def api_actions(request):
    actions = Action.objects.all()
    x = [action.to_json() for action in actions]

    context = {
        "action_list": actions,
    }
    return HttpResponse(x)

def login(request):
    return HttpResponse("Login!")

def api_action(request, action_id):
    pass

bizint/templates/bizint/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>bizint</title>
</head>
<body>
{% if action_list %}
<ul>
    {% for action in action_list %}
    <li><a href="{% url 'bizint:info' action.id %}">{{ action.action_name }}</a> - {{ action.get_current_count }}</li>
    {% endfor %}
</ul>
{% else %}
<p>No action available</p>
{% endif %}
</body>
</html>

bizint/templates/bizint/info.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ action.action_name|default:"Doesn\'t Exist!" }}</title>
</head>
<body>
{% if action %}
<h1>{{ action.action_name }}</h1>
<p>{{ action.get_current_count }}</p>
<a href="{% url 'bizint:add' action.id%}">+1</a>
{% endif %}
</body>
</html>

bizint/templates/bizint/login.html
{% block content %}

{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

{% if next %}
    {% if user.is_authenticated %}
    <p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
    {% else %}
    <p>Please login to see this page.</p>
    {% endif %}
{% endif %}

<form method="post" action="{% url 'bizint:login' %}">
{% csrf_token %}
<table>
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
</tr>
</table>

<input type="submit" value="login">
<input type="hidden" name="next" value="{{ next }}">
</form>


{% endblock %}